/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alkalmfizjegyzek;

/**
 *
 * @author Dávid
 */
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

public class addAlkalmazott extends javax.swing.JFrame {

Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;
    /**
     * Creates new form addAlkalmazott
     */
    public addAlkalmazott() {
        initComponents();
        conn=db.java_db();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        currentDate();
        
    }
   public void toReport(){
        try {               
            JasperReport jasperReport = null;
            InputStream path=this.getClass().getResourceAsStream("report1.jrxml");    
            JasperPrint jasperPrint = null;
            jasperReport = JasperCompileManager.compileReport(path);
            HashMap parameters = new HashMap();
            jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, conn);
            JasperViewer.viewReport(jasperPrint,false);
        } catch (JRException ex) {
            Logger.getLogger(addAlkalmazott.class.getName()).log(Level.SEVERE, null, ex);
        }
}


    public void currentDate(){
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        
        datumjMenu2.setText((month +1)+"/"+day+"/"+year);
        
        int second = cal.get(Calendar.SECOND);
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);
        
        idojMenu3.setText(hour+":"+(minute)+":"+second);
    }
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_keresztnev = new javax.swing.JTextField();
        txt_vezeteknev = new javax.swing.JTextField();
        txt_anyjanev = new javax.swing.JTextField();
        txt_szul = new javax.swing.JTextField();
        txt_telefon = new javax.swing.JTextField();
        txt_ado = new javax.swing.JTextField();
        txt_varos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_reszleg = new javax.swing.JTextField();
        txt_belepes = new javax.swing.JTextField();
        txt_munkakor = new javax.swing.JTextField();
        txt_fizetes = new javax.swing.JTextField();
        txt_lakcim = new javax.swing.JTextField();
        txt_iranyitoszam = new javax.swing.JTextField();
        txt_hazszam = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        r_ferfi = new javax.swing.JRadioButton();
        r_no = new javax.swing.JRadioButton();
        j_kiurites = new javax.swing.JButton();
        j_csatolas = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txt_kereses = new javax.swing.JTextField();
        j_torles = new javax.swing.JButton();
        j_frissites = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        kep = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        datumjMenu2 = new javax.swing.JMenu();
        idojMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setText("Alkalmazott ID:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 110, 80, 30);

        jLabel2.setText("Vezetéknév:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 150, 80, 30);

        jLabel3.setText("Keresztnév:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 190, 80, 30);

        jLabel4.setText("Születési dátum:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 320, 100, 30);

        jLabel5.setText("Házszám:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(390, 150, 60, 30);
        jPanel1.add(txt_id);
        txt_id.setBounds(140, 110, 200, 30);
        jPanel1.add(txt_keresztnev);
        txt_keresztnev.setBounds(140, 190, 200, 30);
        jPanel1.add(txt_vezeteknev);
        txt_vezeteknev.setBounds(140, 150, 200, 30);
        jPanel1.add(txt_anyjanev);
        txt_anyjanev.setBounds(140, 230, 200, 30);
        jPanel1.add(txt_szul);
        txt_szul.setBounds(140, 320, 200, 30);
        jPanel1.add(txt_telefon);
        txt_telefon.setBounds(140, 360, 200, 30);
        jPanel1.add(txt_ado);
        txt_ado.setBounds(140, 400, 200, 30);

        txt_varos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_varosActionPerformed(evt);
            }
        });
        jPanel1.add(txt_varos);
        txt_varos.setBounds(140, 440, 200, 30);

        jLabel6.setText("E-mail címe:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(380, 230, 70, 30);

        jLabel7.setText("Anyja neve:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 230, 80, 30);

        jLabel9.setText("Lakcím:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(400, 110, 50, 30);

        jLabel10.setText("Irányítószám:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(370, 190, 80, 30);

        jLabel13.setText("Telefonszám:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(60, 360, 80, 30);

        jLabel14.setText("Munkakör:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(390, 400, 80, 30);

        jLabel16.setText("Alapfizetés:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(380, 440, 70, 30);

        jLabel15.setText("Belépés ideje:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(370, 360, 90, 30);

        jLabel18.setText("Adóazonosító szám:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(30, 400, 110, 30);

        jLabel12.setText("Város:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(100, 440, 50, 30);

        jLabel17.setText("Részleg:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(400, 320, 60, 30);
        jPanel1.add(txt_email);
        txt_email.setBounds(450, 230, 200, 30);
        jPanel1.add(txt_reszleg);
        txt_reszleg.setBounds(450, 320, 200, 30);
        jPanel1.add(txt_belepes);
        txt_belepes.setBounds(450, 360, 200, 30);
        jPanel1.add(txt_munkakor);
        txt_munkakor.setBounds(450, 400, 200, 30);

        txt_fizetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fizetesActionPerformed(evt);
            }
        });
        jPanel1.add(txt_fizetes);
        txt_fizetes.setBounds(450, 440, 200, 30);
        jPanel1.add(txt_lakcim);
        txt_lakcim.setBounds(450, 110, 200, 30);
        jPanel1.add(txt_iranyitoszam);
        txt_iranyitoszam.setBounds(450, 190, 200, 30);
        jPanel1.add(txt_hazszam);
        txt_hazszam.setBounds(450, 150, 200, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AlkalmFizJegyzek.images/Save-icon.png"))); // NOI18N
        jButton1.setText("Hozzáadás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(550, 500, 140, 50);

        jLabel8.setText("Neme:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(100, 280, 50, 20);

        r_ferfi.setBackground(new java.awt.Color(0, 153, 255));
        r_ferfi.setText("Férfi");
        r_ferfi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_ferfiActionPerformed(evt);
            }
        });
        jPanel1.add(r_ferfi);
        r_ferfi.setBounds(150, 280, 47, 23);

        r_no.setBackground(new java.awt.Color(0, 153, 255));
        r_no.setText("Nő");
        r_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_noActionPerformed(evt);
            }
        });
        jPanel1.add(r_no);
        r_no.setBounds(210, 280, 39, 23);

        j_kiurites.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AlkalmFizJegyzek.images/erase-128.png"))); // NOI18N
        j_kiurites.setText("Kiürítés");
        j_kiurites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_kiuritesActionPerformed(evt);
            }
        });
        jPanel1.add(j_kiurites);
        j_kiurites.setBounds(710, 440, 140, 50);

        j_csatolas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AlkalmFizJegyzek.images/attach.png"))); // NOI18N
        j_csatolas.setText("Kép csatolása");
        j_csatolas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_csatolasActionPerformed(evt);
            }
        });
        jPanel1.add(j_csatolas);
        j_csatolas.setBounds(710, 500, 140, 50);

        jLabel11.setText("Keresés:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(90, 40, 42, 14);

        txt_kereses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_keresesActionPerformed(evt);
            }
        });
        txt_kereses.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_keresesKeyReleased(evt);
            }
        });
        jPanel1.add(txt_kereses);
        txt_kereses.setBounds(140, 30, 480, 30);

        j_torles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AlkalmFizJegyzek.images/delete_16x16.gif"))); // NOI18N
        j_torles.setText("Törlés");
        j_torles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_torlesActionPerformed(evt);
            }
        });
        jPanel1.add(j_torles);
        j_torles.setBounds(400, 560, 140, 50);

        j_frissites.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AlkalmFizJegyzek.images/update icon.png"))); // NOI18N
        j_frissites.setText("Frissítés");
        j_frissites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_frissitesActionPerformed(evt);
            }
        });
        jPanel1.add(j_frissites);
        j_frissites.setBounds(550, 560, 140, 50);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AlkalmFizJegyzek.images/logout_1.png"))); // NOI18N
        jButton2.setText("Visszalépés");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(710, 560, 140, 50);

        jDesktopPane1.setLayer(kep, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kep, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kep, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jDesktopPane1);
        jDesktopPane1.setBounds(680, 110, 240, 200);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AlkalmFizJegyzek.images/addAlkalmazott.jpg"))); // NOI18N
        jLabel20.setText("jLabel20");
        jLabel20.setRequestFocusEnabled(false);
        jPanel1.add(jLabel20);
        jLabel20.setBounds(0, 0, 1970, 630);

        datumjMenu2.setText("Dátum");
        jMenuBar1.add(datumjMenu2);

        idojMenu3.setText("Idő");
        jMenuBar1.add(idojMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 935, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_noActionPerformed

        neme= "Nő";
        r_no.setSelected(true);
        r_ferfi.setSelected(false);
    }//GEN-LAST:event_r_noActionPerformed

    private void r_ferfiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_ferfiActionPerformed

        neme = "Férfi";
        r_ferfi.setSelected(true);
        r_no.setSelected(false);
    }//GEN-LAST:event_r_ferfiActionPerformed

    private void txt_varosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_varosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_varosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //az adatbázishoz hozzáadok adatokat
        int x = JOptionPane.showConfirmDialog(null,"Biztos hozzá akarod adni az adatbázishoz?","Hozzáadva",JOptionPane.YES_NO_OPTION );
        if (x==0){
            try { String sql ="insert into Staff_information "
                + "(Vezeteknev,Keresztnev,Szuletesi_datum,Email,"
                + "Telefon,Cím,Varos,"
                + "Kep,Fizetes,Neme,Anyjaneve,"
                + "Iranyitoszam, Reszleg,Adoszam,Munkakor,Hazszam,Belepes) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ";

                pst=conn.prepareStatement(sql);
                pst.setString(1,txt_vezeteknev.getText());
                pst.setString(2,txt_keresztnev.getText());
                pst.setString(3,txt_szul.getText());
                pst.setString(4,txt_email.getText());
                pst.setString(5,txt_telefon.getText());
                pst.setString(6,txt_lakcim.getText());
                pst.setString(7,txt_varos.getText());
                pst.setBytes(8, person_image);

                pst.setString(9,txt_fizetes.getText());
                pst.setString(10, neme);
                pst.setString(11,txt_anyjanev.getText());
                pst.setString(12,txt_iranyitoszam.getText());
                pst.setString(13,txt_reszleg.getText());
                pst.setString(14,txt_ado.getText());
                pst.setString(15,txt_munkakor.getText());
                pst.setString(16,txt_hazszam.getText());
                pst.setString(17,txt_belepes.getText());

                pst.execute();
                JOptionPane.showMessageDialog(null,"Adatok elmentve");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e);
            }

            finally {

                try{
                    rs.close();
                    pst.close();

                }
                catch(Exception e){

                }

            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_fizetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fizetesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fizetesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        MainMenu p = new MainMenu();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void j_frissitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_frissitesActionPerformed
        //a meglévő adatokat frissítem újjakra
        String val12 = txt_id.getText();
        int x = JOptionPane.showConfirmDialog(null,"Biztos frissíteni  akarod az adatbázist?","Frissítve",JOptionPane.YES_NO_OPTION );
        if (x==0){
            try {

                String val =   txt_vezeteknev.getText();
                String val2 =  txt_keresztnev.getText();
                String val3 =  txt_szul.getText();
                String val4 =  txt_anyjanev.getText();
                String val5 =  txt_email.getText();
                String val6 =  txt_lakcim.getText();
                String val7 =  txt_hazszam.getText();
                String val8 =  txt_iranyitoszam.getText();
                String val9 =  txt_telefon.getText();
                String val10 = txt_reszleg.getText();
                String val11 = txt_fizetes.getText();
                String val15 = txt_ado.getText();
                String val13 = txt_belepes.getText();
                String val14 = txt_munkakor.getText();
                

                String val16 = txt_varos.getText();

                String sql = "update Staff_information set id = '"+val12+"',Vezeteknev = '"+val+"', Keresztnev ='"+val2+"',"
                + "Szuletesi_datum ='"+val3+"', Anyjaneve = '"+val4+"', Email ='"+val5+"', Telefon = '"+val9+"',"
                + "Cím = '"+val6+"', Varos = '"+val16+"', Iranyitoszam = '"+val8+"', Reszleg= '"+val10+"',"
                + "Fizetes = '"+val11+"',Belepes='"+val13+"',Munkakor= '"+val14+"',Hazszam = '"+val7+"',"
                + "Adoszam = '"+val15+"',Neme = '"+neme+"' , Kep =? where id = '"+val12+"'  ";

                pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Adatok frissítve!");

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, e);

            }finally{

                try {

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);

                }
                try{
                    File file = new File(filename);
                    FileInputStream fis = new FileInputStream(file);
                    byte [] image = new byte[(int) file.length()];
                    fis.read(image);

                    String sql = "update Staff_information set Kep =? where id = '"+val12+"' ";

                    pst= conn.prepareStatement(sql);
                    pst.setBytes(1, image);
                    pst.executeUpdate();
                    pst.close();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);

                }
                finally{
                    try{
                        rs.close();
                        pst.close();

                    }catch (Exception e){

                    }
                }
            }
        }
    }//GEN-LAST:event_j_frissitesActionPerformed

    private void j_torlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_torlesActionPerformed
        
        //az adatbázisból kitörlöm az akkor beírt id-ju tartalmat
        int x = JOptionPane.showConfirmDialog(null,"Biztos törölni akarod az adatbáziból?","Törölve",JOptionPane.YES_NO_OPTION );
        if (x==0){
            try {
                String sql = "delete from Staff_information where id=?";
                pst=conn.prepareStatement(sql);
                pst.setString(1,txt_id.getText());
                pst.execute();

                JOptionPane.showMessageDialog(null, "Adatok törölve");

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null,e);
            }finally {//takaritó kód

                try{
                    rs.close();
                    pst.close();
                }
                catch(Exception e){

                }
            }

        }
    }//GEN-LAST:event_j_torlesActionPerformed

    private void txt_keresesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_keresesKeyReleased
        //kereső menü megjeleníti az ehhez az id-hoz való tartalmat
        try{
            String sql ="select * from Staff_information where id=? ";
            pst=conn.prepareStatement(sql);
            pst.setString(1,txt_kereses.getText());
            rs=pst.executeQuery();

            String add1 =rs.getString("id");
            txt_id.setText(add1);
            String add2 =rs.getString("Vezeteknev");
            txt_vezeteknev.setText(add2);
            String add3 =rs.getString("Keresztnev");
            txt_keresztnev.setText(add3);
            String add4 =rs.getString("Szuletesi_datum");
            txt_szul.setText(add4);
            String add5 =rs.getString("Email");
            txt_email.setText(add5);
            String add6 =rs.getString("Telefon");
            txt_telefon.setText(add6);
            String add7 =rs.getString("Cím");
            txt_lakcim.setText(add7);
            String add8 =rs.getString("Anyjaneve");
            txt_anyjanev.setText(add8);
            String add10 =rs.getString("Fizetes");
            txt_fizetes.setText(add10);
            String add11 =rs.getString("Varos");
            txt_varos.setText(add11);
            String add12 =rs.getString("Hazszam");
            txt_hazszam.setText(add12);
            String add13 =rs.getString("Iranyitoszam");
            txt_iranyitoszam.setText(add13);
            String add14 =rs.getString("Adoszam");
            txt_ado.setText(add14);
            String add15 =rs.getString("Belepes");
            txt_belepes.setText(add15);
            String add16 =rs.getString("Munkakor");
            txt_munkakor.setText(add16);
            String add17 =rs.getString("Reszleg");
            txt_reszleg.setText(add17);
            String add18 = rs.getString("Neme");
            if(add18.equals("Férfi")){
                r_ferfi.setSelected(true);
                r_no.setSelected(false);
            }else{
                r_no.setSelected(true);
                r_ferfi.setSelected(false);
            }
            byte[] image = rs.getBytes("Kep");
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(image).getImage().getScaledInstance(kep.getWidth(), kep.getHeight(), Image.SCALE_SMOOTH));
            kep.setIcon(imageIcon);

        }catch(Exception e){
        }
        finally {
            try{

                rs.close();
                pst.close();

            } catch(Exception e){

            }
        }
    }//GEN-LAST:event_txt_keresesKeyReleased

    private void j_csatolasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_csatolasActionPerformed
        //fénykép hozzá csatolása
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();

        filename = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon (new ImageIcon(filename).getImage().getScaledInstance(kep.getWidth(),kep.getHeight(),Image.SCALE_DEFAULT));
        kep.setIcon(imageIcon);

        try{

            File image = new File(filename);
            FileInputStream fix = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];

            for(int number;(number = fix.read(buf))!= -1;){ //bemenet elfogyott(-1) bezárja

                bos.write(buf,0,number);
            }
            person_image = bos.toByteArray();

        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_j_csatolasActionPerformed

    private void j_kiuritesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_kiuritesActionPerformed
        
        txt_kereses.setText("");
        txt_ado.setText("");
        txt_anyjanev.setText("");
        txt_belepes.setText("");
        txt_email.setText("");
        txt_fizetes.setText("");
        txt_hazszam.setText("");
        txt_id.setText("");
        txt_iranyitoszam.setText("");
        txt_keresztnev.setText("");
        txt_lakcim.setText("");
        txt_munkakor.setText("");
        txt_reszleg.setText("");
        txt_szul.setText("");
        txt_telefon.setText("");
        txt_varos.setText("");
        txt_vezeteknev.setText("");
        kep.setIcon(null);
    }//GEN-LAST:event_j_kiuritesActionPerformed

    private void txt_keresesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_keresesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_keresesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addAlkalmazott.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addAlkalmazott.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addAlkalmazott.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addAlkalmazott.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addAlkalmazott().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu datumjMenu2;
    private javax.swing.JMenu idojMenu3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton j_csatolas;
    private javax.swing.JButton j_frissites;
    private javax.swing.JButton j_kiurites;
    private javax.swing.JButton j_torles;
    private javax.swing.JLabel kep;
    private javax.swing.JRadioButton r_ferfi;
    private javax.swing.JRadioButton r_no;
    private javax.swing.JTextField txt_ado;
    private javax.swing.JTextField txt_anyjanev;
    private javax.swing.JTextField txt_belepes;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_fizetes;
    private javax.swing.JTextField txt_hazszam;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_iranyitoszam;
    private javax.swing.JTextField txt_kereses;
    private javax.swing.JTextField txt_keresztnev;
    private javax.swing.JTextField txt_lakcim;
    private javax.swing.JTextField txt_munkakor;
    private javax.swing.JTextField txt_reszleg;
    private javax.swing.JTextField txt_szul;
    private javax.swing.JTextField txt_telefon;
    private javax.swing.JTextField txt_varos;
    private javax.swing.JTextField txt_vezeteknev;
    // End of variables declaration//GEN-END:variables

    //fényképhez:
    private ImageIcon format = null;
    String filename = null;
    byte[] person_image = null;
    
    
    
    private String neme;


}


