/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alkalmfizjegyzek;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Dávid
 */
public class Fizetes extends javax.swing.JFrame {
    
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form Fizetes
     */
    public Fizetes() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
        
        conn=db.java_db();
        currentDate();
        
}
    
    public void currentDate(){
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        
        datumjMenu2.setText((month +1)+"/"+day+"/"+year);
        
        int second = cal.get(Calendar.SECOND);
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);
        
        idojMenu3.setText(hour+":"+(minute)+":"+second);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        r_szazalek = new javax.swing.JRadioButton();
        r_osszeg = new javax.swing.JRadioButton();
        txt_kereses = new javax.swing.JTextField();
        txt_vezeteknev = new javax.swing.JTextField();
        txt_keresztnev = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_szul = new javax.swing.JTextField();
        txt_fizetes = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_alkid = new javax.swing.JTextField();
        txt_reszleg = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_szazalek = new javax.swing.JTextField();
        txt_osszeg = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        datumjMenu2 = new javax.swing.JMenu();
        idojMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setText("Alkalmazott ID:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 140, 90, 30);

        jLabel2.setText("Vezetéknév:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 180, 80, 30);

        jLabel3.setText("Keresztnév:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 220, 80, 30);

        jLabel4.setText("Fizetés emelés:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(180, 280, 110, 30);

        r_szazalek.setText("Százalék(%)");
        r_szazalek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_szazalekActionPerformed(evt);
            }
        });
        jPanel1.add(r_szazalek);
        r_szazalek.setBounds(280, 280, 100, 30);

        r_osszeg.setText("Összeg");
        r_osszeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_osszegActionPerformed(evt);
            }
        });
        jPanel1.add(r_osszeg);
        r_osszeg.setBounds(400, 280, 90, 30);

        txt_kereses.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_keresesKeyReleased(evt);
            }
        });
        jPanel1.add(txt_kereses);
        txt_kereses.setBounds(120, 30, 470, 30);
        jPanel1.add(txt_vezeteknev);
        txt_vezeteknev.setBounds(100, 180, 200, 30);
        jPanel1.add(txt_keresztnev);
        txt_keresztnev.setBounds(100, 220, 200, 30);

        jLabel5.setText("Születési Dátum:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(390, 140, 100, 30);

        jLabel6.setText("Fizetés:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(430, 220, 60, 30);
        jPanel1.add(txt_szul);
        txt_szul.setBounds(480, 140, 200, 30);
        jPanel1.add(txt_fizetes);
        txt_fizetes.setBounds(480, 220, 200, 30);

        jLabel7.setText("Alkalmazott ID:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(33, 30, 90, 30);
        jPanel1.add(txt_alkid);
        txt_alkid.setBounds(100, 140, 200, 30);
        jPanel1.add(txt_reszleg);
        txt_reszleg.setBounds(480, 180, 200, 30);

        jLabel8.setText("Részleg:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(430, 180, 70, 30);

        txt_szazalek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_szazalekActionPerformed(evt);
            }
        });
        jPanel1.add(txt_szazalek);
        txt_szazalek.setBounds(280, 320, 100, 30);
        jPanel1.add(txt_osszeg);
        txt_osszeg.setBounds(400, 320, 90, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AlkalmFizJegyzek.images/Save-icon.png"))); // NOI18N
        jButton1.setText("Hozzáadás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(570, 310, 130, 50);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AlkalmFizJegyzek.images/logout_1.png"))); // NOI18N
        jButton2.setText("Visszalépés");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(570, 380, 130, 50);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AlkalmFizJegyzek.images/money1.jpg"))); // NOI18N
        jLabel9.setMaximumSize(new java.awt.Dimension(0, 0));
        jLabel9.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(-410, 0, 1170, 450);

        jMenu1.setText("File");

        jMenuItem1.setText("Mentés Excelbe");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        datumjMenu2.setText("Dátum");
        jMenuBar1.add(datumjMenu2);

        idojMenu3.setText("Idő");
        jMenuBar1.add(idojMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int fizetes = Integer.parseInt(txt_fizetes.getText());
        
        try{
        if(r_szazalek.isSelected()==true){    
            
        //metódus 1:
        int getPercentage = Integer.parseInt(txt_szazalek.getText()); 
        int calcPercentage = fizetes/100 * getPercentage + fizetes;//százalékos emelés
        String xP = String.valueOf(calcPercentage);
        txt_fizetes.setText(xP);
        }else if(r_osszeg.isSelected()==true){
        //metódus 2:
        int getAmt = Integer.parseInt(txt_osszeg.getText());
        int calcAmount = fizetes +getAmt;  //összeg emelés
        String xA = String.valueOf(calcAmount);
        txt_fizetes.setText(xA);
        }
        
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        try {
            String value1 = txt_alkid.getText();
            String value2 = txt_fizetes.getText();
            
            
            String sql = "update Staff_information set id = '"+value1+"',Fizetes ='"+value2+"' where id = '"+value1+"'   ";
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Adatbázis frissítve");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            try {
                rs.close();
                pst.close();
                
                
            } catch (Exception e) {
            }
        }         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void r_osszegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_osszegActionPerformed
        
        r_osszeg.setSelected(true);
        r_szazalek.setSelected(false);
        txt_szazalek.setEnabled(false);
        txt_osszeg.setEditable(true);
        txt_osszeg.setEnabled(true);
        txt_osszeg.setText("");
            
    }//GEN-LAST:event_r_osszegActionPerformed

    private void txt_szazalekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_szazalekActionPerformed
           
    }//GEN-LAST:event_txt_szazalekActionPerformed

    private void txt_keresesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_keresesKeyReleased
        
             try{
            String sql ="select * from Staff_information where id=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1,txt_kereses.getText());
            rs=pst.executeQuery();
            
            String add1 =rs.getString("id");
            txt_alkid.setText(add1);
            String add2 =rs.getString("Vezeteknev");
            txt_vezeteknev.setText(add2);
            String add3 =rs.getString("Keresztnev");
            txt_keresztnev.setText(add3);
            String add4 =rs.getString("Szuletesi_datum");
            txt_szul.setText(add4);
            String add10 =rs.getString("Fizetes");
            txt_fizetes.setText(add10);
            String add17 =rs.getString("Reszleg");
            txt_reszleg.setText(add17);
            
            
        }catch(Exception e){
        }
        finally {
            try{
                
                rs.close();
                pst.close();
                
            } catch(Exception e){
                
        } 
    }
    }//GEN-LAST:event_txt_keresesKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        MainMenu k = new MainMenu();
        k.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void r_szazalekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_szazalekActionPerformed
        
        r_osszeg.setSelected(false);
        r_szazalek.setSelected(true);
        txt_szazalek.setEnabled(true);
        txt_osszeg.setEditable(false);
        txt_osszeg.setEnabled(false);
        txt_szazalek.setText("");   
    }//GEN-LAST:event_r_szazalekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fizetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fizetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fizetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fizetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fizetes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu datumjMenu2;
    private javax.swing.JMenu idojMenu3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton r_osszeg;
    private javax.swing.JRadioButton r_szazalek;
    private javax.swing.JTextField txt_alkid;
    private javax.swing.JTextField txt_fizetes;
    private javax.swing.JTextField txt_kereses;
    private javax.swing.JTextField txt_keresztnev;
    private javax.swing.JTextField txt_osszeg;
    private javax.swing.JTextField txt_reszleg;
    private javax.swing.JTextField txt_szazalek;
    private javax.swing.JTextField txt_szul;
    private javax.swing.JTextField txt_vezeteknev;
    // End of variables declaration//GEN-END:variables
}
