/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alkalmfizjegyzek;

import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.imageio.ImageIO;
import javax.swing.*;

/**
 *
 * @author Dávid
 */
public class Kereses extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
   
    public Kereses() {
        initComponents();
        conn=db.java_db();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        currentDate();
        
    }
    public void currentDate(){
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        
        datumjMenu2.setText((month +1)+"/"+day+"/"+year);
        
        int second = cal.get(Calendar.SECOND);
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);
        
        idojMenu3.setText(hour+":"+(minute)+":"+second);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        j_kiurites1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_kereses = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_reszleg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_belepes = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        txt_munkakor = new javax.swing.JTextField();
        txt_keresztnev = new javax.swing.JTextField();
        txt_fizetes = new javax.swing.JTextField();
        txt_vezeteknev = new javax.swing.JTextField();
        txt_lakcim = new javax.swing.JTextField();
        txt_anyjanev = new javax.swing.JTextField();
        txt_szul = new javax.swing.JTextField();
        txt_iranyitoszam = new javax.swing.JTextField();
        txt_hazszam = new javax.swing.JTextField();
        txt_telefon = new javax.swing.JTextField();
        txt_ado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_varos = new javax.swing.JTextField();
        r_ferfi = new javax.swing.JRadioButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        kep = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        r_no = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        datumjMenu2 = new javax.swing.JMenu();
        idojMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        j_kiurites1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AlkalmFizJegyzek.images/erase-128.png"))); // NOI18N
        j_kiurites1.setText("Kiürítés");
        j_kiurites1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_kiurites1ActionPerformed(evt);
            }
        });
        jPanel1.add(j_kiurites1);
        j_kiurites1.setBounds(760, 460, 130, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AlkalmFizJegyzek.images/logout_1.png"))); // NOI18N
        jButton3.setText("Visszalépés");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(760, 530, 130, 40);

        jLabel7.setText("Anyja neve:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 220, 90, 30);

        jLabel9.setText("Lakcím:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(410, 90, 70, 30);

        jLabel10.setText("Irányítószám:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(380, 170, 90, 30);

        jLabel13.setText("Telefonszám:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(40, 360, 110, 30);

        jLabel14.setText("Munkakör:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(400, 360, 80, 30);

        jLabel16.setText("Alapfizetés:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(390, 460, 70, 30);

        jLabel11.setText("Keresés:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(42, 34, 70, 20);

        txt_kereses.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_keresesKeyReleased(evt);
            }
        });
        jPanel1.add(txt_kereses);
        txt_kereses.setBounds(120, 30, 560, 30);

        jLabel15.setText("Belépés ideje:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(380, 310, 80, 30);

        jLabel18.setText("Adóazonosító szám:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(10, 410, 110, 30);

        jLabel1.setText("Alkalmazott ID:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 90, 100, 30);

        jLabel12.setText("Város:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(71, 460, 40, 30);

        jLabel2.setText("Vezetéknév:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 130, 80, 30);

        jLabel17.setText("Részleg:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(410, 410, 70, 30);

        jLabel3.setText("Keresztnév:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 170, 80, 30);
        jPanel1.add(txt_email);
        txt_email.setBounds(460, 220, 220, 30);

        jLabel4.setText("Születési dátum:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 310, 120, 30);
        jPanel1.add(txt_reszleg);
        txt_reszleg.setBounds(460, 410, 220, 30);

        jLabel5.setText("Házszám:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(400, 130, 70, 30);
        jPanel1.add(txt_belepes);
        txt_belepes.setBounds(460, 310, 220, 30);
        jPanel1.add(txt_id);
        txt_id.setBounds(120, 90, 220, 30);
        jPanel1.add(txt_munkakor);
        txt_munkakor.setBounds(460, 360, 220, 30);
        jPanel1.add(txt_keresztnev);
        txt_keresztnev.setBounds(120, 170, 220, 30);

        txt_fizetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fizetesActionPerformed(evt);
            }
        });
        jPanel1.add(txt_fizetes);
        txt_fizetes.setBounds(460, 460, 220, 30);
        jPanel1.add(txt_vezeteknev);
        txt_vezeteknev.setBounds(120, 130, 220, 30);
        jPanel1.add(txt_lakcim);
        txt_lakcim.setBounds(460, 90, 220, 30);
        jPanel1.add(txt_anyjanev);
        txt_anyjanev.setBounds(120, 220, 220, 30);
        jPanel1.add(txt_szul);
        txt_szul.setBounds(120, 310, 220, 30);
        jPanel1.add(txt_iranyitoszam);
        txt_iranyitoszam.setBounds(460, 170, 220, 30);
        jPanel1.add(txt_hazszam);
        txt_hazszam.setBounds(460, 130, 220, 30);

        txt_telefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefonActionPerformed(evt);
            }
        });
        jPanel1.add(txt_telefon);
        txt_telefon.setBounds(120, 360, 220, 30);
        jPanel1.add(txt_ado);
        txt_ado.setBounds(120, 410, 220, 30);

        jLabel8.setText("Neme:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(70, 270, 70, 20);

        txt_varos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_varosActionPerformed(evt);
            }
        });
        jPanel1.add(txt_varos);
        txt_varos.setBounds(120, 460, 220, 30);

        r_ferfi.setBackground(new java.awt.Color(0, 153, 255));
        r_ferfi.setText("Férfi");
        r_ferfi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_ferfiActionPerformed(evt);
            }
        });
        jPanel1.add(r_ferfi);
        r_ferfi.setBounds(120, 270, 50, 23);

        jDesktopPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        kep.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        kep.setLabelFor(jDesktopPane1);

        jDesktopPane1.setLayer(kep, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jDesktopPane1);
        jDesktopPane1.setBounds(710, 50, 240, 200);

        jLabel6.setText("E-mail címe:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(390, 220, 70, 30);

        r_no.setBackground(new java.awt.Color(51, 153, 255));
        r_no.setText("Nő");
        r_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_noActionPerformed(evt);
            }
        });
        jPanel1.add(r_no);
        r_no.setBounds(180, 270, 50, 23);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AlkalmFizJegyzek.images/addAlkalmazott.jpg"))); // NOI18N
        jPanel1.add(jLabel19);
        jLabel19.setBounds(0, 0, 970, 640);

        datumjMenu2.setText("Dátum");
        jMenuBar1.add(datumjMenu2);

        idojMenu3.setText("Idő");
        jMenuBar1.add(idojMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 967, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_keresesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_keresesKeyReleased

        try{
            String sql ="select * from Staff_information where id=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1,txt_kereses.getText());
            rs=pst.executeQuery();

            String add1 =rs.getString("id");
            txt_id.setText(add1);
            String add2 =rs.getString("Vezeteknev");
            txt_vezeteknev.setText(add2);
            String add3 =rs.getString("Keresztnev");
            txt_keresztnev.setText(add3);
            String add4 =rs.getString("Szuletesi_datum");
            txt_szul.setText(add4);
            String add5 =rs.getString("Email");
            txt_email.setText(add5);
            String add6 =rs.getString("Telefon");
            txt_telefon.setText(add6);
            String add7 =rs.getString("Cím");
            txt_lakcim.setText(add7);
            String add8 =rs.getString("Anyjaneve");
            txt_anyjanev.setText(add8);
            String add10 =rs.getString("Fizetes");
            txt_fizetes.setText(add10);
            String add11 =rs.getString("Varos");
            txt_varos.setText(add11);
            String add12 =rs.getString("Hazszam");
            txt_hazszam.setText(add12);
            String add13 =rs.getString("Iranyitoszam");
            txt_iranyitoszam.setText(add13);
            String add14 =rs.getString("Adoszam");
            txt_ado.setText(add14);
            String add15 =rs.getString("Belepes");
            txt_belepes.setText(add15);
            String add16 =rs.getString("Munkakor");
            txt_munkakor.setText(add16);
            String add17 =rs.getString("Reszleg");
            txt_reszleg.setText(add17);
            String add18 = rs.getString("Neme");
            if(add18.equals("Férfi")){
                r_ferfi.setSelected(true);
                r_no.setSelected(false);
                
            }else{
                r_no.setSelected(true);
                r_ferfi.setSelected(false);
            }
            byte[] image = rs.getBytes("Kep");
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(image).getImage().getScaledInstance(kep.getWidth(), kep.getHeight(), Image.SCALE_SMOOTH));
            kep.setIcon(imageIcon);

        }catch(Exception e){
        }
        finally {
            try{

                rs.close();
                pst.close();

            } catch(Exception e){

            }
        }

    }//GEN-LAST:event_txt_keresesKeyReleased

    private void txt_fizetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fizetesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fizetesActionPerformed

    private void txt_varosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_varosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_varosActionPerformed

    private void r_ferfiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_ferfiActionPerformed

        neme = "Férfi";
        r_ferfi.setSelected(true);
        r_no.setSelected(false);
    }//GEN-LAST:event_r_ferfiActionPerformed

    private void r_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_noActionPerformed

        neme= "Nő";
        r_no.setSelected(true);
        r_ferfi.setSelected(false);

    }//GEN-LAST:event_r_noActionPerformed

    private void txt_telefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefonActionPerformed

    private void j_kiurites1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_kiurites1ActionPerformed

        txt_kereses.setText("");
        txt_ado.setText("");
        txt_anyjanev.setText("");
        txt_belepes.setText("");
        txt_email.setText("");
        txt_fizetes.setText("");
        txt_hazszam.setText("");
        txt_id.setText("");
        txt_iranyitoszam.setText("");
        txt_keresztnev.setText("");
        txt_lakcim.setText("");
        txt_munkakor.setText("");
        txt_reszleg.setText("");
        txt_szul.setText("");
        txt_telefon.setText("");
        txt_varos.setText("");
        txt_vezeteknev.setText("");
        kep.setIcon(null);

    }//GEN-LAST:event_j_kiurites1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        MainMenu p = new MainMenu();
        p.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kereses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kereses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kereses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kereses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kereses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu datumjMenu2;
    private javax.swing.JMenu idojMenu3;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton j_kiurites1;
    private javax.swing.JLabel kep;
    private javax.swing.JRadioButton r_ferfi;
    private javax.swing.JRadioButton r_no;
    private javax.swing.JTextField txt_ado;
    private javax.swing.JTextField txt_anyjanev;
    private javax.swing.JTextField txt_belepes;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_fizetes;
    private javax.swing.JTextField txt_hazszam;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_iranyitoszam;
    private javax.swing.JTextField txt_kereses;
    private javax.swing.JTextField txt_keresztnev;
    private javax.swing.JTextField txt_lakcim;
    private javax.swing.JTextField txt_munkakor;
    private javax.swing.JTextField txt_reszleg;
    private javax.swing.JTextField txt_szul;
    private javax.swing.JTextField txt_telefon;
    private javax.swing.JTextField txt_varos;
    private javax.swing.JTextField txt_vezeteknev;
    // End of variables declaration//GEN-END:variables
   
    private ImageIcon format = null;
    String filename = null;
    byte[] person_image = null;
    
    
    
    private String neme;
}
